// alias: "";
categoria_transporte: "2";
// categoria_traslado: "";
// client_lastname: "";
// client_mail: "hector@gmail.com";
// client_name: "Hector Sanchez";
// client_phone: "9999999999";
// codigo: "";
// comments: "";
// currency: "MXN";
// destino: "HX";
end_date: "2025-07-13";
fecha_limite_pago: "";
// habitacion: "";
hora: "00:00:00";
hora_llegada: "";
hora_salida: "";
hotel: "Bahía Huatulco";
// id_dealer: "";
// id_proveedor: "";
// id_servicio: "1";
// id_usuario: "2";
// infantes: "0";
// limit_customer: "10/07/2025";
// limit_payment: "INMEDIATO";
// nombre_producto: "";
numero_vuelo: "fff";
numero_vuelo_salida: "";
// pagado: "0";
// pax_adults: "2";
// pax_menor: "0";
pickup: "23:40";
pickup_salida: "";
// product_code: "54";
// rate_code: "96";
start_date: "2025-07-10";
tipo_viaje: "HA";
total: "760";
// vendedor_referenciado: "";
// zona_hotel: "A";
